<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>JellyfinLegendaz</AssemblyName>
    <RootNamespace>JellyfinLegendaz</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" />
    <PackageReference Include="Jellyfin.Model"      Version="10.11.11" />
    <PackageReference Include="Newtonsoft.Json"     Version="13.0.3"   />
  </ItemGroup>

</Project>
